version: '3.8'
services:
  db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: kudconnect
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

  keycloak:
    image: kudconnect-keycloak:latest
    command: ['start-dev']
    volumes:
      - ./realm-config:/opt/keycloak/data/import
    environment:
      - KC_DB=dev-file
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_FEATURES=scripts
      - KC_HTTP_PORT=9080
      - KUDCONNECT_SERVER_URL=http://host.docker.internal:8080
    ports:
      - "9080:9080"

volumes:
  postgres_data: