#management.tracing.enabled: true
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kudconnect
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  modulith:
    events:
      jdbc-schema-initialization:
        enabled: true