#management.tracing.enabled: true
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.base-url}/realms/kudconnect
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/demodb}
    username: ${POSTGRES_USER:kudconnect}
    password: ${POSTGRES_PASSWORD:ctdkucoonn}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  modulith:
    events:
      jdbc-schema-initialization:
        enabled: true

jwt:
  auth:
    converter:
      resource-id: kudconnect-webapp
      principle-attribute: preferred_username

keycloak:
  base-url: ${KEYCLOAK_BASE_URL:http://localhost:9080}

logging:
  level:
    root: INFO

